package games;
import java.util.Scanner;
import java.util.Random;

/**
 * The purpose of this program is to have a user try to guess a randomly generated 
 * number. 
 * 
 * @author evanspat
 * Date Created 7/12/2016
 */
public class NumberGame
{

	public static void main(String[] args)
	{
		//Create a new Random()
		Random random = new Random();
		
		//Create randomly generated number from 0 to 1000 inclusive. 
		int computerNum = random.nextInt(1001);
		
		//Print out the greeting and directions.
		System.out.println("Hello. Please guess a number between 0 and 1,000.");

		//Create a new Scanner(), reading from the keyboard (System.in)
		Scanner input = new Scanner(System.in);
		
		//Read the user's next integer input.
		int userNum= input.nextInt();

		//Create a boolean variable that evaluates to true if the game is over or false if the game is not over.
		boolean gameOver = false;

		//The game is not considered over until the user guesses the correct number. While the game is still running,
		//give the program user hints as to how high or low their number is. 
		while (!gameOver)
		{
			//Check to see if the user's number is less than the number generated by the computer.
			if (userNum < computerNum)
			{
				//Tell the user their guess is too low and suggest guessing higher.
				System.out.println("Your number is too low, try again! Guess Higher.");
			}
			//If not less than, let's check greater than.
			else if (userNum > computerNum)
			{
				//Tell the user their guess is too high and suggest they guess lower.
				System.out.println("Your number is too high, try again! Guess Lower.");
			}
			//If it's not greater than or less than, they must be equal!
			else
			{
				//Congratulate the user on winning.
				System.out.println("Congratulations, you've guessed the correct number!");

				//Give the user the option to play again. 
				System.out.println("Would you like to play again?  Please write yes or no.");
				//Store the user's input into a variable.
				String userInput = input.next();
				//Compare the input with the word yes
				if(userInput.equals("yes"))
				{
					//The user has decided to play again, print the opening statement again
					System.out.println("Thank you for playing again! Please guess a number between 0 and 1,000.");
					//Create a new number between 0 and 1000 inclusive
					computerNum = (int)(Math.random() * 1000 + 1);
				}
				else
				{
					//The game is now over we need to stop the while loop.
					gameOver=true;
					
					//Tell the user the game has finished.
					System.out.println("GAME OVER");
					
					//This exits the game
					System.exit(0);
				}
			}
			//If we get to this point, the user didn't guess correctly, we need to get their next guess.
			userNum = input.nextInt();
		}
		//This closes the scanner
		input.close();
	}
}